"""Add updated_at column to Ticket model

Revision ID: 66236a658566
Revises: 86665469aa69
Create Date: 2024-01-31 15:49:11.681369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66236a658566'
down_revision = '86665469aa69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
