"""Add full_name column to ticket table

Revision ID: 86665469aa69
Revises: 56c56a539f2e
Create Date: 2024-01-25 17:27:39.250946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86665469aa69'
down_revision = '56c56a539f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
